"""empty message

Revision ID: 104efac049e8
Revises: efe26e3f05c7
Create Date: 2022-02-14 05:40:09.636152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '104efac049e8'
down_revision = 'efe26e3f05c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ShoppingList',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('checked', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    seed_list = table('ShoppingList',
                      column('user_id', sa.Integer),
                      column('content', sa.Text),
                      column('checked', sa.Boolean)
                      )
    op.bulk_insert(seed_list, [
                   {'user_id': '1', 'content': '아이스크림', 'checked': False}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ShoppingList')
    # ### end Alembic commands ###
