"""empty message

Revision ID: 2b997e774d61
Revises: 35b2449a81ab
Create Date: 2022-02-19 16:11:12.957425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from datetime import datetime
from pytz import timezone


# revision identifiers, used by Alembic.
revision = '2b997e774d61'
down_revision = '35b2449a81ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Refrigerator',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('content', sa.VARCHAR(
                        length=255), nullable=False),
                    sa.Column('category', sa.Integer(), nullable=True),
                    sa.Column('time', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category'], ['IngrdCategory.category'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    seed_items = table('Refrigerator',
                       column('user_id', sa.Integer),
                       column('content', sa.VARCHAR),
                       column('category', sa.Integer),
                       column('time', sa.DateTime),
                       )
    items = [
        {'user_id': 1, 'content': '고추장', 'category': 6,
            'time': datetime.now(timezone('Asia/Seoul'))}
    ]
    op.bulk_insert(seed_items, items)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Refrigerator')
    # ### end Alembic commands ###
