"""empty message

Revision ID: 35b2449a81ab
Revises: 10f60713d026
Create Date: 2022-02-19 14:39:00.878616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from data.seed_data_read import get_ingrds

# revision identifiers, used by Alembic.
revision = '35b2449a81ab'
down_revision = '10f60713d026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IngrdCategory',
                    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('category', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('category')
                    )
    op.create_table('Ingredients',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('category', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category'], ['IngrdCategory.category'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    seed_categories = table('IngrdCategory',
                            column('name', sa.VARCHAR),
                            column('category', sa.Integer),
                            )
    categories = [
        {'name': '과일', 'category': 1},
        {'name': '채소', 'category': 2},
        {'name': '육류', 'category': 3},
        {'name': '해산물', 'category': 4},
        {'name': '유제품', 'category': 5},
        {'name': '소스류', 'category': 6},
        {'name': '기타', 'category': 7}
    ]
    op.bulk_insert(seed_categories, categories)

    seed_ingrds = table('Ingredients',
                        column('name', sa.VARCHAR),
                        column('category', sa.Integer),
                        )
    ingrds = get_ingrds()
    op.bulk_insert(seed_ingrds, ingrds)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ingredients')
    op.drop_table('IngrdCategory')
    # ### end Alembic commands ###
