"""empty message

Revision ID: 7ee3494a8723
Revises: 2b997e774d61
Create Date: 2022-02-21 01:40:42.777974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '7ee3494a8723'
down_revision = '2b997e774d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bookmark',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.Column('checked', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('UserLike',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.Column('checked', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    seed_bookmark = table('Bookmark',
                          column('user_id', sa.Integer),
                          column('recipe_id', sa.Integer),
                          column('checked', sa.Boolean),
                          )
    op.bulk_insert(seed_bookmark, [
                   {'user_id': 1, 'recipe_id': 1, 'checked': True}])

    seed_userlike = table('UserLike',
                          column('user_id', sa.Integer),
                          column('recipe_id', sa.Integer),
                          column('checked', sa.Boolean),
                          )
    op.bulk_insert(seed_userlike, [
                   {'user_id': 1, 'recipe_id': 1, 'checked': True}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserLike')
    op.drop_table('Bookmark')
    # ### end Alembic commands ###
