"""empty message

Revision ID: de37eb3461f5
Revises: 2d3db6c1a387
Create Date: 2022-02-17 17:03:15.824239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = 'de37eb3461f5'
down_revision = '2d3db6c1a387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IngrdCategory',
                    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('category', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('category')
                    )
    op.create_table('Ingredients',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('category', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category'], ['IngrdCategory.category'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    seed_categories = table('IngrdCategory',
                            column('name', sa.VARCHAR),
                            column('category', sa.Integer),
                            )
    categories = [
        {'name': '과일', 'category': 1},
        {'name': '채소해조', 'category': 2},
        {'name': '수조어육', 'category': 3},
        {'name': '음료및차', 'category': 4},
        {'name': '유제품빙과', 'category': 5},
        {'name': '장류양념류', 'category': 6},
        {'name': '기타', 'category': 7}
    ]
    op.bulk_insert(seed_categories, categories)

    seed_ingrds = table('Ingredients',
                        column('name', sa.VARCHAR),
                        column('category', sa.Integer),
                        )
    ingrds = [
        {'name': '딸기', 'category': 1},
        {'name': '당근', 'category': 2},
        {'name': '닭가슴살', 'category': 3},
        {'name': '와인', 'category': 4},
        {'name': '우유', 'category': 5},
        {'name': '고추장', 'category': 6},
        {'name': '누텔라', 'category': 7}
    ]
    op.bulk_insert(seed_ingrds, ingrds)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ingredients')
    op.drop_table('IngrdCategory')
    # ### end Alembic commands ###
