"""empty message

Revision ID: e5eb6470bba5
Revises: fec985a8ee49
Create Date: 2022-03-11 11:58:03.946493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5eb6470bba5'
down_revision = 'fec985a8ee49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Bookmark_ibfk_2', 'Bookmark', type_='foreignkey')
    op.create_foreign_key(None, 'Bookmark', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Refrigerator_ibfk_2', 'Refrigerator', type_='foreignkey')
    op.create_foreign_key(None, 'Refrigerator', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ShoppingList_ibfk_1', 'ShoppingList', type_='foreignkey')
    op.create_foreign_key(None, 'ShoppingList', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('UserLike_ibfk_2', 'UserLike', type_='foreignkey')
    op.create_foreign_key(None, 'UserLike', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserLike', type_='foreignkey')
    op.create_foreign_key('UserLike_ibfk_2', 'UserLike', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'ShoppingList', type_='foreignkey')
    op.create_foreign_key('ShoppingList_ibfk_1', 'ShoppingList', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'Refrigerator', type_='foreignkey')
    op.create_foreign_key('Refrigerator_ibfk_2', 'Refrigerator', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'Bookmark', type_='foreignkey')
    op.create_foreign_key('Bookmark_ibfk_2', 'Bookmark', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
