"""empty message

Revision ID: efe26e3f05c7
Revises: 
Create Date: 2022-02-11 16:07:09.443365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'efe26e3f05c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
    seed_users = table('User',
        column('name', sa.String),
        column('email', sa.String),
        column('password', sa.String),
    )
    op.bulk_insert(seed_users, [{'name':'gokuma', 'email': 'admin@gokuma.com','password':'password'}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
